UIFC-358: Update results if deleting search string via keyboard
folio-org/ui-plugin-find-finc-metadata-collection pull request #114
Opened 2024-10-17 08:38 UTC by elsenhans

https://folio-org.atlassian.net/browse/UIFC-358

2024-10-17 10:12 UTC, alb3rtino requested changes

2024-10-17 10:12 UTC, alb3rtino commented on src/CollectionView.test.js
The added test does not test what you want it to test.

`await userEvent.type(inputField, ' ');`
This sets the the search field to a single whitespace character instead of an empty string. `e.target.value` will evaluate to `true` and the reset method is not even being called here.

You are testing the rendering behaviour of the component with different props. But what you actually want to test is if the `getSearchHandlers().reset()` method is called if you change the input to an empty string (`''`).

2024-10-17 11:48 UTC, elsenhans commented on src/CollectionView.test.js
replaced it with `await userEvent.clear(inputField);`

2024-10-17 11:50 UTC, elsenhans commented on src/CollectionView.test.js
> +    const inputField = document.querySelector('#collectionSearchField');
replaced most of the `documents` by `screen`

2024-10-17 11:54 UTC, alb3rtino commented on src/CollectionView.test.js
> +    const inputField = document.querySelector('#collectionSearchField');
Well. I meant in your changes. But ok. :smile:

2024-10-17 11:56 UTC, alb3rtino commented on src/CollectionView.test.js
Good. However, the issue with this test remains; it does not verify whether the `reset()` method is invoked.

2024-10-17 12:01 UTC, elsenhans commented on src/CollectionView.test.js
What do you suggest?
This lines are covered:
![image](https://github.com/user-attachments/assets/769c71af-52b6-4aac-b1e5-f3c87358c3d1)

2024-10-17 14:36 UTC, alb3rtino commented on src/CollectionView.test.js
Coverage shows the code is executed, but the test should verify that `reset()` was actually called. Currently, if you set the search input field to `'abc'` or `' '` (like before), the test still passes. However, in these cases, it should fail. You need to mock the `reset()` method and test that its called using jests `toHaveBeenCalled()`.

2024-10-22 15:13 UTC, alb3rtino approved these changes

2024-10-22 15:17 UTC, merged